"use client"
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "./Providers";
import { ToastContainer } from "react-toastify";
import "react-phone-input-2/lib/style.css";
import useFCM from "@/utils/hooks/useFCM";
import { useEffect } from "react";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Logisitics",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  let { fcmToken }: any = useFCM();

  useEffect(() => {
    if (fcmToken?.length > 0) {
      console.log(fcmToken,"fcmTOken")
      // sendFCMToken();
    }
  }, [fcmToken]);
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <AuthProvider>{children}
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
