import './globals.css'
import { Inter } from 'next/font/google'
import Header from "./components/Header"
import SideBar from "./components/SideBar"
import Signup from './components/Signup/Signup'
import Login from './components/Login/Login'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      {/* <SideBar /> */}
      <Login />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
