"use client"
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "./Providers";
import { ToastContainer } from "react-toastify";
import "react-phone-input-2/lib/style.css";
import useFCM from "@/utils/hooks/useFCM";
import { useEffect } from "react";
import { usePathname } from "next/navigation";
import axiosInstance from "@/services/utils/hooks/useApi";
import { SEND_FCM_TOKEN } from "./constants/apiEndpoints";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Logisitics",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  let { fcmToken }: any = useFCM();

  console.log(pathname,"pathname")


  const sendFCMToken = async () => {
    if (fcmToken) {
      let payload = {
        device_name: "WEB",
        fcm_token: fcmToken,
      };
     const response = await axiosInstance.post(SEND_FCM_TOKEN, payload);
     if(response.status === 200){
      console.log(response,"response...")
     }
    }
  };

  // useEffect(() => {
  //   if (fcmToken?.length > 0 && pathname !== "/") {
  //     console.log(fcmToken,"fcmTOken")
  //     sendFCMToken();
  //   }
  // }, [fcmToken]);
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <AuthProvider>{children}
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
